development:
  adapter: postgresql
  encoding: unicode
  database: popcode_dev
  pool: 5
  username: pkruger
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: popcode_test
  tool: 5
  username: pkruger
  password:

cucumber:
  <<: *test
  username: pkruger
  password:
